# Testing my Drools experiment API

@port=8098
@base=http://127.0.0.1:8098/api/v1/drools

# Base URL
GET {{base}}/ HTTP/1.1


# Test basic rule - discount will be 0.0
GET {{base}}/discount HTTP/1.1
Content-Type: application/json

{
    "name": "Test 1",
    "type": "Test",
    "price": "100.0"
}
